# fly.toml app configuration file generated for atlas-rs on 2024-05-07T01:53:20-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'atlas-rs'
primary_region = 'yyz'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'

[env]
  SWAGGER_UI_ENABLED = "true"
  DB_UPDATE_INTERVAL_SECONDS = "259200"

[mounts]
  source = "atlas_db_data"
  destination = "/opt/atlas/db/"
  initial_size = "2gb"
